[package]
name = "hades-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.2", features = ["derive"] }
lazy_static = "1.4.0"
ron = "0.8.1"
serde = { version = "1.0.197", features = ["derive"] }
