name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Lint:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

  Test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'

      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test
        run: ./gradlew test
      - name: Generate Code Coverage Report
        run: ./gradlew jacocoTestReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Archive Test Results
        if: always() # Even on failures
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: hadesboot/build/reports/tests/test
