---
name: Release Latest

on:
  push:
    tags:
      - "v*"
    branches:
      - master

jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        config:
          - os: "ubuntu-latest"
            distribution: linux-x86_64DistTar
            target: linux-x86_64
          - os: "windows-latest"
            distribution: windows-x86_64DistTar
            target: windows-x86_64
          - os: "macos-latest"
            distribution: macos-x86_64DistTar
            target: macos-x86_64

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 15

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew -x test ${{ matrix.config.distribution }}

      - uses: actions/upload-artifact@v2
        with:
          name: hades-${{ matrix.config.target }}.tar
          path: hadesboot/build/distributions/hades-${{ matrix.config.target }}.tar

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: hades-linux-x86_64.tar
      - uses: actions/download-artifact@v2
        with:
          name: hades-windows-x86_64.tar
      - uses: actions/download-artifact@v2
        with:
          name: hades-macos-x86_64.tar
      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Release latest tag
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          if: github.ref == 'refs/heads/master'
          files: |
            hades-linux-x86_64.tar
            hades-macos-x86_64.tar
            hades-windows-x86_64.tar
      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Release specific version
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          if: github.ref != 'refs/heads/master'
          files: |
            hades-linux-x86_64.tar
            hades-macos-x86_64.tar
            hades-windows-x86_64.tar
